### PR TITLE
Simple hello branch

### PR DESCRIPTION
**Pull request by monicah79**
Added index.html
Installed linters
Added style css
Created .github folder
Followed GitHub flow

### CODE REVIEW

**Review by Lizdev-05 — CHANGES_REQUESTED** [review]
Hi @monicah79 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

so-close

 ## Highlights

- The linters were installed properly and they passed 👍
- The node_modules and test.md were ignored in gitignored ✔
- Most of the requirements of the project are met ✔

 ## Required Changes ♻️

- Kindly add a descriptive README file, you can use this  [README](https://github.com/microverseinc/readme-template/blob/master/README.md) for guidance
- Kindly allow the code reviewers to review your request before merging 😊.
- Kindly read this [GITHub-Flow](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) on how to properly handle your branches😊

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by monicah79** [comment]
hey bt my code  got a read me file

**Comment by monicah79** [comment]
Plus havent merged anything

**Review by Owusu-Desmond — CHANGES_REQUESTED** [review]
Hi @monicah79  :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.



- [x] Please, next time make sure your commit messages are capitalized and descriptive. 
The fist character of the commit message should be capitalized and the commit message should be descriptive. For example, instead of `add readme.md` you can use `Add readme.md` or `Add readme file`. But as you can see you have your commit messages not capitalized. You can read more about it [here](https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/) :pray:

- [ ] You should have added your readme file to this PR so it can be reviewed with inline comments but you need to make the following changes in your readme file.
   - Please make sure that you add the getting started section and make it more descriptive and the content should be the steps to follow to get your project up and running on a local machine. 
  
  For example,
  ```
  You can add the steps to follow to clone your project,
  
  Step 1:if you don't have git installed on your machine you can download it from [here](https://git-scm.com/downloads).
  
  Once you have git installed on your machine you can clone your project by running the command below to clone your project to your local machine
  
  
  `git clone <your project link>`
  
  Alternatively, you can download the zip file of your project by clicking on the `Code` button on the right side of your project page and clicking on `Download ZIP`
  
  Step 2: Locate the folder where you cloned your project to and open the `index.html` file in your browser to view your project.
  ```
## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set of the project ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
